# Generated by Django 4.2 on 2023-05-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_post_alter_comment_author'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_comments',
            field=models.ManyToManyField(related_name='posts', to='comments.comment'),
        ),
    ]
